changed to working scanner and opencv with kivy
fixed previous bug

known bug
- raise RuntimeError("Broken toolchain: cannot link a simple C program")
RuntimeError: Broken toolchain: cannot link a simple C program